version: "3.7"
services:
  app:
    container_name: book-service
    restart: always
    build: .
    ports:
      - "3002:3001"
  mongo:
    container_name: book-mongo
    image: mongo:4.2.1
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: "dbtest"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - ./initdb.js:/docker-entrypoint-initdb.d/initdb.js
      - mongo-db:/data/db
      - mongo-backup:/backup
volumes:
  mongo-db:
  mongo-backup:

